import { User, Student, Trainer, YogaClass, Booking, Subscription, Tariff, Intensive, Group, TrainerStats } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    telegramId: '123456789',
    firstName: 'Анна',
    lastName: 'Иванова',
    username: 'anna_yoga',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anna',
    role: 'STUDENT',
    phone: '+7 (999) 123-45-67',
    email: 'anna@example.com',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    telegramId: '987654321',
    firstName: 'Мария',
    lastName: 'Петрова',
    username: 'maria_petrova',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
    role: 'trainer',
    phone: '+7 (999) 987-65-43',
    email: 'maria@yoga-studio.ru',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    telegramId: '456789123',
    firstName: 'Елена',
    lastName: 'Сидорова',
    username: 'elena_s',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena',
    role: 'STUDENT',
    phone: '+7 (999) 456-78-90',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    telegramId: '789123456',
    firstName: 'Ольга',
    lastName: 'Козлова',
    username: 'olga_kozlova',
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=olga',
    role: 'trainer',
    phone: '+7 (999) 789-12-34',
    email: 'olga@yoga-studio.ru',
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockTrainers: Trainer[] = [
  {
    ...mockUsers[1],
    role: 'trainer',
    bio: 'Сертифицированный инструктор йоги с 10-летним опытом. Специализация: хатха-йога, медитация.',
    specialties: ['hatha', 'meditation'],
    classes: [],
  },
  {
    ...mockUsers[3],
    role: 'trainer',
    bio: 'Инструктор виньяса-йоги. Помогу найти гармонию тела и разума.',
    specialties: ['vinyasa', 'yin'],
    classes: [],
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    studentId: '1',
    type: '8_classes',
    totalClasses: 8,
    usedClasses: 3,
    remainingClasses: 5,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-03-01'),
    status: 'active',
    price: 12000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'sub-2',
    studentId: '3',
    type: '4_classes',
    totalClasses: 4,
    usedClasses: 1,
    remainingClasses: 3,
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-04-01'),
    status: 'active',
    price: 7000,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-05'),
  },
];

export const mockStudents: Student[] = [
  {
    ...mockUsers[0],
    role: 'STUDENT',
    balance: 5,
    subscription: mockSubscriptions[0],
    bookings: [],
  },
  {
    ...mockUsers[2],
    role: 'STUDENT',
    balance: 3,
    subscription: mockSubscriptions[1],
    bookings: [],
  },
];

export const mockYogaClasses: YogaClass[] = [
  {
    id: 'class-1',
    title: 'Утренняя хатха-йога',
    description: 'Бодрящая практика для начала дня. Подходит для всех уровней.',
    type: 'hatha',
    level: 'all',
    trainerId: '2',
    trainer: mockTrainers[0],
    date: new Date(),
    startTime: '08:00',
    endTime: '09:30',
    duration: 90,
    maxStudents: 15,
    enrolledStudents: 8,
    status: 'scheduled',
    location: 'Зал А',
    price: 1500,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-2',
    title: 'Виньяса-флоу',
    description: 'Динамичная практика с плавными переходами между асанами.',
    type: 'vinyasa',
    level: 'intermediate',
    trainerId: '4',
    trainer: mockTrainers[1],
    date: new Date(),
    startTime: '18:00',
    endTime: '19:30',
    duration: 90,
    maxStudents: 12,
    enrolledStudents: 10,
    status: 'scheduled',
    location: 'Зал Б',
    price: 1800,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-3',
    title: 'Йин-йога',
    description: 'Медитативная практика с длительным удержанием поз.',
    type: 'yin',
    level: 'all',
    trainerId: '4',
    trainer: mockTrainers[1],
    date: new Date(),
    startTime: '20:00',
    endTime: '21:15',
    duration: 75,
    maxStudents: 20,
    enrolledStudents: 5,
    status: 'scheduled',
    location: 'Зал А',
    price: 1500,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-4',
    title: 'Медитация и дыхание',
    description: 'Практика осознанности и дыхательных техник.',
    type: 'meditation',
    level: 'all',
    trainerId: '2',
    trainer: mockTrainers[0],
    date: new Date(),
    startTime: '19:00',
    endTime: '20:00',
    duration: 60,
    maxStudents: 25,
    enrolledStudents: 15,
    status: 'scheduled',
    location: 'Медитационный зал',
    price: 1200,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    studentId: '1',
    student: mockStudents[0],
    classId: 'class-1',
    yogaClass: mockYogaClasses[0],
    status: 'confirmed',
    bookedAt: new Date('2024-01-19T10:00:00'),
    notes: 'Первое занятие',
  },
  {
    id: 'booking-2',
    studentId: '1',
    student: mockStudents[0],
    classId: 'class-2',
    yogaClass: mockYogaClasses[1],
    status: 'confirmed',
    bookedAt: new Date('2024-01-18T15:30:00'),
  },
  {
    id: 'booking-3',
    studentId: '3',
    student: mockStudents[1],
    classId: 'class-1',
    yogaClass: mockYogaClasses[0],
    status: 'confirmed',
    bookedAt: new Date('2024-01-19T09:00:00'),
  },
];

export const mockTariffs: Tariff[] = [
  {
    id: 'tariff-1',
    name: 'Разовое занятие',
    type: 'single',
    classesCount: 1,
    price: 1800,
    discountPercent: 0,
    validityDays: 30,
    description: 'Попробуйте йогу без обязательств',
  },
  {
    id: 'tariff-2',
    name: '4 занятия',
    type: '4_classes',
    classesCount: 4,
    price: 7000,
    discountPercent: 8,
    validityDays: 60,
    description: 'Для тех, кто практикует 1 раз в неделю',
  },
  {
    id: 'tariff-3',
    name: '8 занятий',
    type: '8_classes',
    classesCount: 8,
    price: 12000,
    discountPercent: 17,
    validityDays: 90,
    description: 'Для регулярной практики 2 раза в неделю',
    popular: true,
  },
  {
    id: 'tariff-4',
    name: '12 занятий',
    type: '12_classes',
    classesCount: 12,
    price: 16000,
    discountPercent: 25,
    validityDays: 120,
    description: 'Максимальная выгода для активной практики',
  },
];

export const mockIntensives: Intensive[] = [
  {
    id: 'intensive-1',
    title: 'Детокс-интенсив "Очищение"',
    description: '3-дневный интенсив для очищения тела и разума. Включает йогу, дыхательные практики и рекомендации по питанию.',
    trainerId: '2',
    trainer: mockTrainers[0],
    startDate: new Date('2024-02-10'),
    endDate: new Date('2024-02-12'),
    durationDays: 3,
    maxParticipants: 10,
    enrolledParticipants: 6,
    price: 15000,
    status: 'upcoming',
    schedule: ['10:00 - 12:00', '10:00 - 12:00', '10:00 - 12:00'],
    location: 'Зал А',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'intensive-2',
    title: 'Интенсив по инверсиям',
    description: '5-дневный курс для тех, кто хочет освоить стойки на руках и голове.',
    trainerId: '4',
    trainer: mockTrainers[1],
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-03-05'),
    durationDays: 5,
    maxParticipants: 8,
    enrolledParticipants: 4,
    price: 20000,
    status: 'upcoming',
    schedule: ['18:00 - 20:00', '18:00 - 20:00', '18:00 - 20:00', '18:00 - 20:00', '18:00 - 20:00'],
    location: 'Зал Б',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockGroups: Group[] = [
  {
    id: 'group-1',
    name: 'Начинающие',
    trainerId: '2',
    students: [mockStudents[0]],
    schedule: 'Пн, Ср, Пт - 10:00',
    level: 'beginner',
    maxStudents: 15,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'group-2',
    name: 'Продолжающие',
    trainerId: '4',
    students: [mockStudents[1]],
    schedule: 'Вт, Чт - 19:00',
    level: 'intermediate',
    maxStudents: 12,
    createdAt: new Date('2024-01-01'),
  },
];

export const mockTrainerStats: TrainerStats = {
  totalClasses: 156,
  totalStudents: 89,
  totalRevenue: 2450000,
  averageAttendance: 78,
  classesThisMonth: 24,
  studentsThisMonth: 45,
};

export const classTypeLabels: Record<string, string> = {
  hatha: 'Хатха-йога',
  vinyasa: 'Виньяса',
  ashtanga: 'Аштанга',
  yin: 'Йин-йога',
  meditation: 'Медитация',
  intensive: 'Интенсив',
};

export const classLevelLabels: Record<string, string> = {
  beginner: 'Начинающий',
  intermediate: 'Средний',
  advanced: 'Продвинутый',
  all: 'Все уровни',
};

export const bookingStatusLabels: Record<string, string> = {
  confirmed: 'Подтверждено',
  cancelled: 'Отменено',
  completed: 'Завершено',
  no_show: 'Неявка',
};

export const subscriptionTypeLabels: Record<string, string> = {
  single: 'Разовое',
  '4_classes': '4 занятия',
  '8_classes': '8 занятий',
  '12_classes': '12 занятий',
  unlimited: 'Безлимит',
};
